#!/usr/bin/env bun
import { spawn } from "bun";

console.log(`\x1b[36m running backend...\x1b[0m`)
const backend = spawn(["php", "artisan", "serve"], {
  cwd: "./backend",
  stdout: "inherit",
  stderr: "inherit",
});

console.log(`\x1b[36m running frontend...\x1b[0m`);
const frontend = spawn(["npm", "run", "dev"], {
  cwd: "./frontend",
  stdout: "inherit",
  stderr: "inherit",
});

console.log(`
\x1b[32m========================================
  Backend:  ${backend.pid}
  Frontend: ${frontend.pid}
========================================\x1b[0m
`);
